[font]
size = 16

[font.normal]
family = "Iosevka Nerd Font"
style = "Light"

[font.italic]
family = "Iosevka Nerd Font"
style = "Light Italic"

[font.bold]
family = "Iosevka Nerd Font"
style = "SemiBold Oblique"

[scrolling]
history = 20000

[window]
dimensions = { columns = 190, lines = 68 }
decorations = "Buttonless"
opacity = 0.82
blur = true
padding = { x = 4, y = 2}
dynamic_padding = true

[colors.primary]
background = '#202020'
foreground = '#c5c5c5'

[colors.cursor]
text = '#1d1f21'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#c75646'
green   = '#8eb33b'
yellow  = '#d0b03c'
blue    = '#4e90a7'
magenta = '#c8a0d1'
cyan    = '#218693'
white   = '#b0b0b0'

# Bright colors
[colors.bright]
black   = '#5d5d5d'
red     = '#e09690'
green   = '#cdee69'
yellow  = '#ffe377'
blue    = '#9cd9f0'
magenta = '#fbb1f9'
cyan    = '#77dfd8'
white   = '#f7f7f7'
