#!/usr/bin/env bats

load helper

setup() {
	ts_setup
	ts_age_bootstrap
}
teardown() { ts_teardown; }

@test "encrypt/decrypt round-trip" {
	echo "secret" >"${TEST_TMP}/p"
	age_encrypt_file "${TEST_TMP}/p" "${TEST_TMP}/p.age"
	age_decrypt_file "${TEST_TMP}/p.age" "${TEST_TMP}/out"
	run cat "${TEST_TMP}/out"
	[ "$output" = "secret" ]
}

@test "verify_roundtrip passes for a good file and fails for a corrupt one" {
	echo "secret" >"${TEST_TMP}/p"
	age_encrypt_file "${TEST_TMP}/p" "${TEST_TMP}/p.age"
	run age_verify_roundtrip "${TEST_TMP}/p" "${TEST_TMP}/p.age"
	[ "$status" -eq 0 ]
	echo "garbage" >"${TEST_TMP}/p.age"
	run age_verify_roundtrip "${TEST_TMP}/p" "${TEST_TMP}/p.age"
	[ "$status" -ne 0 ]
}

@test "ensure_recipient is idempotent (the duplicate-pubkey bug)" {
	pub="$(age-keygen -y "${AGE_KEYS_FILE}")"
	age_ensure_recipient "$pub" "dup"
	age_ensure_recipient "$pub" "dup"
	count="$(grep -cF "$pub" "${AGE_RECIPIENTS_FILE}")"
	[ "$count" -eq 1 ]
}

@test "age_init does not add the machine key twice" {
	# A second init must not duplicate this machine's recipient block.
	age_init >/dev/null 2>&1 || true
	pub="$(age-keygen -y "${AGE_KEYS_FILE}")"
	count="$(grep -cF "$pub" "${AGE_RECIPIENTS_FILE}")"
	[ "$count" -eq 1 ]
}

@test "master key can always decrypt (machine key removed)" {
	echo "s" >"${TEST_TMP}/p"
	age_encrypt_file "${TEST_TMP}/p" "${TEST_TMP}/p.age"
	rm -f "${AGE_KEYS_FILE}"
	age_decrypt_file "${TEST_TMP}/p.age" "${TEST_TMP}/out"
	run cat "${TEST_TMP}/out"
	[ "$output" = "s" ]
}

@test "recovery key via DOT_RECOVERY_KEY decrypts when machine+master gone" {
	age-keygen -o "${TEST_TMP}/rec.txt" 2>/dev/null
	recpub="$(age-keygen -y "${TEST_TMP}/rec.txt")"
	age_ensure_recipient "$recpub" "rec"
	echo "s" >"${TEST_TMP}/p"
	age_encrypt_file "${TEST_TMP}/p" "${TEST_TMP}/p.age"
	rm -f "${AGE_KEYS_FILE}" "${AGE_MASTER_KEY}"
	export DOT_RECOVERY_KEY="${TEST_TMP}/rec.txt"
	age_decrypt_file "${TEST_TMP}/p.age" "${TEST_TMP}/out"
	run cat "${TEST_TMP}/out"
	[ "$output" = "s" ]
}

@test "master public key is auto-generated by init" {
	[ -f "${AGE_MASTER_PUB}" ]
	[ -f "${AGE_MASTER_KEY}" ]
}
