#!/usr/bin/env zsh
# Install (one or multiple) selected application(s)
# using "brew search" as source input
# mnemonic [B]rew [I]nstall [P]ackage

local inst=$(brew search "$@" | fzf -m)

if [[ $inst ]]; then
  for prog in $(echo $inst);
  do; brew install $prog; done;
fi
