#!/usr/bin/env zsh
# Update (one or multiple) selected application(s)
# mnemonic [B]rew [U]pdate [P]ackage

local upd=$(brew leaves | fzf -m)

if [[ $upd ]]; then
  for prog in $(echo $upd);
  do; brew upgrade $prog; done;
fi
