#!/usr/bin/env zsh
# Find in files using rg and fzf
# mnemonic [F]ind [I]n [F]iles

if [ ! "$#" -gt 0 ]; then
  echo "Need a string to search for!"
  return 1
fi

rg --files-with-matches --no-messages "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}"
