# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  bblack: "#5d5d5d"
  bblue: "#9cd9f0"
  bcyan: "#77dfd8"
  bgreen: "#cdee69"
  blue: "#4e90a7"
  bmagenta: "#fbb1f9"
  bred: "#e09690"
  bwhite: "#f7f7f7"
  byellow: "#ffe377"
  cyan: "#218693"
  green: "#8eb33b"
  magenta: "#c8a0d1"
  red: "#c75646"
  white: "#b0b0b0"
  yellow: "#d0b03c"
secondary_prompt:
  template: "❯❯ "
  foreground: p:green
transient_prompt:
  template: "❯ "
  foreground: p:magenta
console_title_template: "{{if .Root}}<p:red>(root)</>{{end}} {{.PWD}}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: 
    foreground: p:red
    type: root
    style: plain
  - properties:
      cache_duration: none
    template: "{{ if .SSHSession }}<p:bmagneta>\ueba9  </>{{ end }}{{ .UserName }} "
    foreground: p:yellow
    type: session
    style: plain
  - properties:
      cache_duration: none
      style: full
    template: "{{ .Path }} "
    foreground: p:blue
    type: path
    style: plain
  - properties:
      branch_ahead_icon: <p:bcyan>⇡ </>
      branch_behind_icon: <p:bcyan>⇣ </>
      branch_icon: "\ue0a0 "
      cache_duration: none
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
      github_icon: ""
    template: "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<p:bmagenta>*</>{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
    foreground: p:bblack
    type: git
    style: plain
  newline: true
- type: prompt
  alignment: right
  segments:
  - properties:
      cache_duration: none
    template: " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }}\uf487 {{.Version}}{{ end }} {{ if .Name }}{{ .Name }}{{ end }}{{ end }} "
    foreground: "#ffe377"
    type: project
    style: plain
  - properties:
      cache_duration: none
    template: "\ue626 {{ .Full }} "
    foreground: "#7FD5EA"
    type: go
    style: plain
  - properties:
      cache_duration: none
    template: " \ue620 {{ .Full }} "
    foreground: "#4e90a7"
    type: lua
    style: plain
  - properties:
      cache_duration: none
    template: " \ue718 {{ .Full }} "
    foreground: "#6CA35E"
    type: node
    style: plain
  - properties:
      cache_duration: none
    template: "\ue71e {{ .Full }} "
    foreground: "#ffeb3b"
    type: npm
    style: plaint
  - properties:
      cache_duration: none
    template: " \U000f1617 {{ .Full }} "
    foreground: "#99908a"
    type: rust
    style: plaint
  - properties:
      cache_duration: none
    template: " \ue738 {{ .Full }}"
    foreground: "#4063D8"
    type: java
    style: plain
  - properties:
      cache_duration: none
    template: " \U000f1219 {{ .Full }} "
    foreground: "#906cff"
    type: kotlin
    style: plain
- type: rprompt
  alignment: right
  filler: .
  overflow: hide
  segments:
  - properties:
      cache_duration: none
    template: "{{ if gt .Code 0}}\U000f1238[{{ .Code }}]{{ end }}"
    foreground: p:red
    type: status
    style: plain
  - properties:
      cache_duration: none
      style: austin
    template: " {{ .FormattedMs }} "
    foreground: p:magenta
    type: executiontime
    style: plain
- type: prompt
  alignment: left
  segments:
  - properties:
      always_enabled: true
      cache_duration: none
    template: ❯
    foreground: p:green
    type: status
    style: plain
    foreground_templates:
    - "{{ if gt .Code 0 }}p:bred{{ end }}"
  newline: true
version: 3
final_space: true
