gui:
  shortTimeFormat: '15:04'
  nerdFontsVersion: '3'
  showDivergenceFromBaseBranch: 'arrowAndNumber'
  spinner:
    frames:
      - '⣽'
      - '⣻'
      - '⢿'
      - '⡿'
      - '⣟'
      - '⣯'
      - '⣷'
      - '⣾'

git:
  paging:
    pager: 'diff-so-fancy'
  mainBranches:
    - 'master'
    - 'main'
    - 'prod'
    - 'production'
  skipHookPrefix: 'WIP'
  commitPrefix:
    pattern: "^\\w+\\/(\\w+-\\d+).*"
    replace: '[$1] '

os:
  editPreset: 'nvim'

disableStartupPopups: true
notARepository: 'skip'

customCommands:
  - key: 'n'
    context: 'files'
    description: 'Commit witout signing'
    subprocess: false
    stream: true
    prompts:
      - type: 'input'
        title: 'Enter commit message'
        key: 'commitMessage'
        initialValue: ''
    command: 'git commit --no-gpg-sign -m {{.Form.commitMessage | quote}}'
  - key: 'n'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git flow {{.Form.BranchType}} start {{.Form.BranchName}}"
    loadingText: 'Creating branch'
